# Configuration principale
spring:
  profiles:
    active: dev
  
  application:
    name: zelare-backend
  
  # Base de données PostgreSQL
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/zelare_db
    username: ${DB_USERNAME:zelare_user}
    password: ${DB_PASSWORD:zelare_password}
  
  # JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  
  # JSON configuration
  jackson:
    time-zone: Africa/Luanda
    date-format: yyyy-MM-dd HH:mm:ss

# Configuration JWT
app:
  jwt:
    secret: ${JWT_SECRET:zelareSuperSecretKeyForJWTTokenGenerationAndValidation2024}
    expiration: 86400000 # 24 heures en millisecondes
    refresh-expiration: 604800000 # 7 jours en millisecondes

# Configuration SMS (Twilio)
twilio:
  account-sid: ${TWILIO_ACCOUNT_SID:your_account_sid}
  auth-token: ${TWILIO_AUTH_TOKEN:your_auth_token}
  phone-number: ${TWILIO_PHONE_NUMBER:your_twilio_phone_number}

# Configuration OTP
otp:
  length: 6
  expiration-minutes: 5
  max-attempts: 3

# Configuration CORS
cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:19006
    - exp://192.168.1.*
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

# Logging
logging:
  level:
    com.zelare.backend: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([%t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /api

---
# Configuration développement
spring:
  config:
    activate:
      on-profile: dev
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    root: INFO
    com.zelare.backend: DEBUG

---
# Configuration production
spring:
  config:
    activate:
      on-profile: prod
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    root: WARN
    com.zelare.backend: INFO